export const piadas = [
  "Por que o livro de matemática odiou o livro de história? - Porque tinha muitos problemas com o passado.",
  "O que a estrela do mar disse para a estrela da noite? - Boa noite, estrela.",
  "Por que o esqueleto não brigou com ninguém? - Porque não tinha estômago para isso.",
  "Qual é o contrário de volátil? - Vem cá, sobrinho!",
  "Por que o pato disse para a pata? - Vem quá!",
  "Qual é o café que não é seu? - De ning uém.",
  "Por que o livro de matemática pulou da estante? - Porque ele tinha muitos problemas.",
  "O que é um pontinho preto no meio do caminho? - Um formiguento.",
  "O que o pente falou para o cabelo? - Não desgruda de mim!",
  "O que aconteceu com o elevador quando ele soube de uma fofoca? - Ele ficou descerro!",
  "O que o nariz falou para o dedo? - Você está vermelho, você está gripado?",
  "Qual é o cúmulo da indecisão? - Não sei.",
  "O que o coração disse para o rim? - Você é um órgão vital!",
  "Por que a pátria-mãe mandou o filho para a cama? - Porque estava estatalado.",
  "Qual é o animal mais antigo? - A zebra, porque está sempre às listras.",
  "O que o zero disse para o oito? - Prazer, cinto de gordo.",
  "O que o pneu falou para o carro? - Não sai da minha esteira.",
  "O que a luz falou para o carro? - Nada, ela só acendeu.",
  "Por que a vassoura não quis sair com o aspirador? - Porque ele só sugava.",
  "O que um tomate falou para o outro? - Você é um pimentão!",
  "O que o palito de fósforo falou para a vela? - Hoje você está acesa.",
  "O que a pia disse para a banheira? - Você me dá banho.",
  "O que um espelho disse para o outro espelho? - A gente se reflete.",
  "O que um peixe falou para o outro peixe? - Você gosta de mim porque sou engraçado?",
  "Por que o cavalo fechou os olhos enquanto passava na frente da loja? - Porque ele tinha medo do preços.",
  "Por que o lápis não foi à festa? - Porque ele não foi bem apontado.",
  "Por que o esqueleto não brigou com ninguém? - Porque não tinha estômago para isso.",
  "Qual é o esporte mais saudável? - A ginástica, porque é uma corrida para a saúde.",
  "O que um lápis falou para o outro lápis? - Você é um traço legal!",
  "Por que o giz foi à escola? - Para ensinar as crianças.",
  "O que o advogado disse para o réu? - Você está preso!",
  "Por que o sorvete foi ao psiquiatra? - Porque estava derretido.",
  "Qual é o meio mais seguro de enviar dinheiro pelo correio? - O selo.",
  "O que é um pontinho vermelho no meio do salão? - Uma menstruação interrompida.",
  "O que o salmão disse ao peixe-espada? - Você é uma bala na água.",
  "O que o pato falou para a pata? - Vem quá.",
  "Por que o rato entrou na escola? - Para aprender rato-mética.",
  "O que o parafuso disse para a porca? - Nós formamos um belo casal.",
  "O que o dedo do pé falou para o dedo da mão? - Não estou gostando da maneira como você anda.",
  "Por que a matemática é triste? - Porque tem problemas.",
  "Por que a chuva é a melhor em qualquer relacionamento? - Porque ela é molhada.",
  "O que o sinal de trânsito falou para o carro? - Não me siga, estou perdido.",
  "O que um muro disse para o outro muro? - Nos encontramos no canto.",
  "O que a mão direita disse para a esquerda? - É melhor você sair por aí.",
  "O que a impressora disse para o papel? - Esse papel vai entrar em história.",
  "O que o morcego disse para o morcego-vampiro? - Estou de olho em você.",
  "O que o passarinho falou para o outro passarinho? - Está na hora de pôr ovo.",
  "O que o lago disse para o outro lago? - Você lago muito.",
  "O que a melancia falou para a melancia? - Melancia-ade você.",
  "O que a água disse para o sabão? - Não sou um sabão em pó, mas tô em pó de você.",
];
